version: '3'

services:
  mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      TZ: "Europe/London"
      MONGO_INITDB_DATABASE: fabidb
    ports:
      - 27017:27017
    